### ISSUE TITLE
Text in localizable strings

### ISSUE THREAD

**Issue by vadymmarkov** [hyperoslo/TimeAgo#15]
@richardoti @zenangst I don't see the point to use "ago" in the text. Also strings like "hours" and "minutes" are too long and it takes a lot of space.
I think it's better to have "25 min" instead of "25 minutes ago", etc. The only issue I see there is that we've already have a lot of localisation files, and we could change it for languages we know like English, Norwegian, but we are not confident about others.

**Comment by richardoti** [comment]
I think, you've mentioned the details of actual implementation. How about changing strings in bundle for the particular app(s)? 

 "25 minutes ago" is a general case and if it does not suits us, we could go to a specific one, adjusting bundle for the particular apps.

We could also take a look on Instagram, it uses "5m", "19h", "3d" and "14w" strings and never goes beyond "weeks"]

**Comment by vadymmarkov** [comment]
Changing strings in bundle for the particular app also makes sense. But I don't know any app with the format like "25 minutes ago", and not sure if someone wants to have it.

**Comment by richardoti** [comment]
![screen shot 2015-06-10 at 10 09 05](https://cloud.githubusercontent.com/assets/8013017/8077781/f72ae964-0f58-11e5-89bd-893b611f5ff1.png)
vk.com - full string


![screen shot 2015-06-10 at 10 11 16](https://cloud.githubusercontent.com/assets/8013017/8077796/2267895c-0f59-11e5-8288-5f560e24a3ba.png)
facebook.com - short one

**Comment by vadymmarkov** [comment]
Ok, let's not overcomplicate it :smiley:
