### ISSUE TITLE
Never use hardcoded values

### ISSUE THREAD

**Issue by zenangst** [hyperoslo/TimeAgo#7]
Instead of having hardcoded values we should consider adding constants.

https://github.com/hyperoslo/TimeAgo/blob/master/Source/NSDate%2BTimeAgo.swift#L22

**Comment by richardoti** [comment]
Don't think, it is good idea here. With constants it would be more difficult to read, while with hardcoded values code is understandable. It may be specific case, where hard-coded values are better. Generally, Im also against them.
